# Generated by Django 3.1.7 on 2021-03-21 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('S', 'success'), ('D', 'danger'), ('W', ' warning'), ('I', 'info'), ('L', 'light'), ('DA', 'dark')], default='P', max_length=5),
            preserve_default=False,
        ),
    ]
