# Generated by Django 3.1.7 on 2021-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210321_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='links',
            field=models.URLField(default='p', max_length=300),
            preserve_default=False,
        ),
    ]
